FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm build

ENV MONGODB_USERNAME=root
ENV MONGODB_PASSWORD=secret
ENV NODE_ENV=development
ENV PORT=8080
ENV LOGINSECRET=somesupersecretsecret
ENV REFRESHSECRET=anothersupersecretsecret

EXPOSE 8080

CMD ["npm", "run", "server"]